version: '3.4'
services:
  thewaytogerman.front:
    image: thewaytogermanfront
    restart: on-failure
    ports:    
      - 6080:80    
    build:
      context: .
      dockerfile: Dockerfile
    
