version: '3.4'
services:
  thewaytogerman.front:
    image: thewaytogermanfront
    restart: on-failure
    ports:    
      - 6080:3000
    environment:
     NODE_ENV: "prod"  
    build:
      context: .
      dockerfile: Dockerfile
    
