name: Deploy to Amazon ECS
on:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - name: install dependencies
        run: |
          npm ci
          npm install -D tailwindcss postcss autoprefixer
          npx tailwindcss init -p
          
      - name: build
        run: npm run build --if-present
        
        
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Create SSH Key File      
        run: |        
          echo "${{ secrets.EC2_SSH_KEY }}" >> ../key.pem
          sudo chmod 600 ../key.pem
      - name: Prepare for Deployment
        run: |  
          ssh -o StrictHostKeyChecking=no -i ../key.pem  ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}  "mkdir -p ~/${{ secrets.Target }}/ ;  rm ~/${{ secrets.Target }}/* -rf"
       
      - name: Deploy code to EC2 instance
        run: |  
         rsync -v -Pav -e "ssh -o StrictHostKeyChecking=no -i ../key.pem  " . ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/${{ secrets.Target }}/
         
      - name: Run code on EC2 instance
        run: |  
         ssh -o StrictHostKeyChecking=no -i ../key.pem  ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}  "cd ~/${{ secrets.Target }}/ ; sudo docker-compose -p "the_way_to_german_front" up --build -d"
       
      - name: Remove SSH Key File     
        run:  sudo rm  ../key.pem      
